# Generated by Django 4.0.4 on 2022-05-10 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2)),
                ('postcode', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=254)),
                ('practice', models.CharField(default='', max_length=254, null=True)),
                ('profession', models.CharField(default='', max_length=254, null=True)),
                ('useremail', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('user_type', models.CharField(choices=[('AD', 'Administrator'), ('MD', 'medical'), ('PA', 'patient')], default='PA', max_length=2)),
                ('phone_number', models.CharField(default='', max_length=200, unique=True)),
                ('verify_code', models.CharField(max_length=10, null=True)),
                ('verify_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
